apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: demo
type: Opaque
data:
  mysql-root-password: YmYxN3RrNmQ3dDU2
  redis-password: YmYxN3RrNmQ3dDU2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-mysql
  template:
    metadata:
      labels:
        app: demo-mysql
    spec:
      containers:
        - name: mysql
          image: docker.io/library/mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: mysql-root-password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-redis
  template:
    metadata:
      labels:
        app: demo-redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: redis-password
          command: ["sh", "-c", "exec redis-server --requirepass $REDIS_PASSWORD"]
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demo-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 32000

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo
spec:
  type: NodePort
  selector:
    app: demo-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 32001

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: demo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi