name: Go

on:
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - "README.*"
      - "LICENSE"
      - "assets/**"
      - "docs/**"
      - ".github/**"
      - ".gitignore"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20.x", "1.21.x"]
        include:
          - go: 1.21.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false # managed by golangci-lint

      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Download Dependencies
        run: |
          go mod download

      - name: Lint & Build
        run: |
          just fmt
          just lint
          just build